const statements = [
    "Fortuna kołem się toczy",
    "Bez pracy nie ma kołaczy",
    "Nosił wilk razy kilka ponieśli i wilka",
    "Czego Jaś się nie nauczy tego Jan nie będzie umiał",
    "W marcu jak w garncu",
    "Nie dziel skóry na niedźwiedziu",
    "Jakby kózka nie skakała to by nóżki nie złamała",
    "Jak się ma co się lubi to się kradnie co popadnie",
    "Nie ma dymu bez ognia",
    "Nie taki diabeł straszny jak go malują",
    "Uderz w stół a nożyce się odezwą",
    "Nie ma róży bez kolców",
    "Gdy w grudniu śnieg pada drugi taki sam rok zapowiada",
    "Gdy w styczniu deszcz leje złe robi nadzieje",
    "Daj kurze grzędę a wyżej jeszcze siędę",
    "Kto rano wstaje temu staje",
    "Czy hrabina czy kucharka byle była w kroku szparka",
    "Kto rano wstaje temu Pan Bóg daje",
    "A co po czyjej wielkości jak nie ma w głowie mądrości",
    "Będą takie mrozy że przymarznie cap do kozy",
    "W maju jak w gaju",
    "Kto pod kim dołki kopie ten sam w nie wpada",
    "Jeśli wpadniesz między wrony musisz krakać tak jak one",
    "Każdy kij ma dwa końce",
    "Do trzech razy sztuka"
];
