@startuml

class Keyboard {
    + drawKeys()
    + onClick(figure)
    - figures
}
class Password {
    + selectPassword(): password
    + drawHiddenPassword()
    + showFigure(figure)
    - win()
    - statements
    - selectedPassword
}
class HangMan {
    + drawNextImage()
    - failed()
}
class Validator {
    + validatePassword(figure): bool
    + subscribe(Action, function(figure))
}
class Game {
    - draw()
    - subscribe()
}

enum Action {
    Ok,
    Nok
}

Keyboard "1" --* "1" Game
Game "1" *-- "1" HangMan
Game "1" *-- "1" Password
Game "1" *-- "1" Validator


Keyboard -left-> "1" Validator
@enduml
